from settings import *

SCREEN_PADDING = 16
HOME_HORIZONTAL_PADDING = 100
ELEMENT_HEIGHT = 50

ELEMENT_WIDTH_LARGE = 500
ELEMENT_WIDTH_SMALL = 236

GAP_BETWEEN_ELEMENT = 32
GAP_BETWEEN_ELEMENT_LABEL = 24

SEPARATOR_LINE_WIDTH =  SCREEN_WIDTH - HOME_HORIZONTAL_PADDING*2