import math

SCREEN_HEIGHT = 700
SCREEN_WIDTH = 1200
SCREEN_BACKGROUND = '#111211'

FPS = 60

DEFAULT_USER_POS_X = 1
DEFAULT_USER_POS_Y = 1
DEFAULT_USER_ROT = math.pi / 4
USER_INTERACTION_AREA = 0.5

# Time in sec
EFFECT_VODKA_TIME = 10

MAX_ITEM_SLOTS = 4

RENDER_DISTANCE = 7
MINIMAP_USER_AREA_DISTANCE = 7