# Generated by Django 6.0.3 on 2026-04-07 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id_account', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
