# Generated by Django 6.0.3 on 2026-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
