# Generated by Django 6.0.3 on 2026-04-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
    ]
