import math

SCREEN_HEIGHT = 700
SCREEN_WIDTH = 1200
SCREEN_BACKGROUND = '#111211'

IS_KEYBOARD_QWERTZ = True

FPS = 60

DEFAULT_USER_POS_X = 1
DEFAULT_USER_POS_Y = 1
DEFAULT_USER_ROT = math.pi / 4
USER_INTERACTION_AREA = 0.5

# Time in sec
EFFECT_VODKA_TIME = 10

MAX_ITEM_SLOTS = 4

RENDER_DISTANCE = 7
MINIMAP_USER_AREA_DISTANCE = 7
NUMBERS_CODE_NEED_WIN = 5
MAX_USER_BATTERY = 1200
BATTERY_CAPACITY = 250
GAME_DURATION = 20 * 60
ZOMBIE_DAMAGE=3